server:
  port: 3000
  autobahnConnection: 'ws://localhost:8090/ws'
  publishTopic: 'com.myapp.hello'
  subscribeTopic: 'io.crossbar.demo.pubsub.404890'

db:
  host: 'localhost'
  type: 'postgres'
  port: 5432
  database: 'taskmanagement'
  synchronize: true
  username: 'postgres'
  password: 'postgres'

jwt:
  expiresIn: 3600
