server:
  port: 3000
  autobahnConnection: ' ws://54.176.243.182:8090/ws'
  publishTopic: 'com.myapp.hello'
  publishTopicActivity: 'com.myapp.activity'
  subscribeTopic: 'io.crossbar.demo.pubsub.404890'
  subscribeTopicActivity: 'io.crossbar.demo.pubsub.404892'

db:
  host: 'localhost'
  type: 'postgres'
  port: 5432
  database: 'taskmanagement'
  synchronize: true
  username: 'postgres'
  password: 'postgres'

jwt:
  expiresIn: 3600
