server:
  origin: https://thingdev.surge.sh
  autobahnConnection: 'ws://localhost:8090/ws'
  publishTopic: 'com.myapp.hello'
  subscribeTopic: 'io.crossbar.demo.pubsub.404890'
db:
  host: 'simplethings-do-user-4182007-0.b.db.ondigitalocean.com'
  type: 'postgres'
  port: 25060
  database: 'defaultdb'
  synchronize: true
  username: 'doadmin'
  password: 'm3uion3zfz74g385'

jwt:
  expiresIn: 3600
  secret: 'topSecret51'
