name: Pull Request

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: github checkout
        uses: actions/checkout@v2
      - name: build
        run: yarn --cwd backend/

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.6.8 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'devsimplethings'
          heroku_email: 'minh@thing.com'
          appdir: 'backend'
          healthcheck: 'https://devsimplethings.herokuapp.com/api'
          delay: 5
        env:
          NODE_ENV: staging

  deploy_frontend:
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: yarn --cwd frontend/
      - name: build
        run: yarn --cwd frontend/ build:stage
      - name: Deploy to thingdev.surge.sh
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: 'thingdev.surge.sh'
          project: 'frontend/dist/'
          login: ${{ secrets.SURGE_LOGIN }}
          token: ${{ secrets.SURGE_TOKEN }}
